SET IDENTITY_INSERT [dbo].[medicines] ON
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (1, N'3456', N'Acetaminophen', 23, 123)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (2, N'123', N'Adderall', 10, 456)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (3, N'3457', N'Alprazolam', 1, 20)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (4, N'3458', N'Citalopram', 0, 345)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (5, N'4567', N'Doxycycline', 67, 10)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (6, N'4568', N'Gabapentin', 2, 500)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (7, N'4569', N'Metformin', 89, 56)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (8, N'4570', N'Metoprolol', 123, 23)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (9, N'4571', N'Naproxen', 0, 89)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (10, N'4581', N'Omeprazole', 0, 14)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (14, N'2314', N'Oxycodone', 7, 59)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (17, N'1234', N'Dolo', 234, 34)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (18, N'3456', N'citrizen', 34, 2)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (1017, N'1691', N'Zincold', 4, 23)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (2017, N'101', N'Chrosine', 2, 5)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (2018, N'1231', N'Heloo', 3, 6)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (2019, N'1231', N'Dart', 12, 24)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (3017, N'0987', N'Ting', 34, 2)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (3018, N'8765', N'Tong', 5, 12)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (4017, N'12', N'venky', 3, 1)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (5017, N'777', N'dfff', 3, 2)
INSERT INTO [dbo].[medicines] ([sno], [medId], [medName], [medUnits], [unitPrice]) VALUES (6017, N'55555', N'newMedicine', 5, 55)
SET IDENTITY_INSERT [dbo].[medicines] OFF
